<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sys_user_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->sys_user_id	= 'ID';
		$this->sys_user_nmuser	= 'NMUSER';
		$this->sys_user_address	= 'ADDRESS';
		$this->sys_user_phone	= 'PHONE';
		$this->sys_user_name	= 'NAME';
		$this->sys_user_email	= 'EMAIL';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_nmuser	= 'nmuser';
		$this->f_address	= 'address';
		$this->f_phone	= 'phone';
		$this->f_name	= 'name';
		$this->f_email	= 'email';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			$this->f_id	=> $this->sys_user_id,
			$this->f_nmuser	=> $this->sys_user_nmuser,
			$this->f_address	=> $this->sys_user_address,
			$this->f_phone	=> $this->sys_user_phone,
			$this->f_name	=> $this->sys_user_name,
			$this->f_email	=> $this->sys_user_email,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2021-01-26 22:56:40 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

